# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Camera(object):
    def setupUi(self, Camera):
        Camera.setObjectName("Camera")
        Camera.resize(972, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Camera.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Camera)
        self.centralwidget.setObjectName("centralwidget")
        self.captureWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.captureWidget.setGeometry(QtCore.QRect(670, 29, 291, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.captureWidget.sizePolicy().hasHeightForWidth())
        self.captureWidget.setSizePolicy(sizePolicy)
        self.captureWidget.setObjectName("captureWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.absenceNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.absenceNumber.setGeometry(QtCore.QRect(10, 80, 261, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absenceNumber.sizePolicy().hasHeightForWidth())
        self.absenceNumber.setSizePolicy(sizePolicy)
        self.absenceNumber.setObjectName("absenceNumber")
        self.SaveButton = QtWidgets.QPushButton(self.tab_2)
        self.SaveButton.setGeometry(QtCore.QRect(10, 20, 261, 51))
        self.Newtemplate= QtWidgets.QPushButton(self.tab_2)
        self.Newtemplate.setGeometry(QtCore.QRect(10, 405,261,40))
        font = QtGui.QFont()
        font_2=QtGui.QFont()
        font.setPointSize(16)
        font_2.setPointSize(12)
        font.setItalic(False)
        self.Newtemplate.setFont(font_2)
        self.Newtemplate.setObjectName("Newtemplate")
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 200, 261, 200))
        self.textBrowser.setObjectName("textBrowser")
        self.captureWidget.addTab(self.tab_2, "")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(10, 30, 640, 480))
        self.img_label.setFrameShape(QtWidgets.QFrame.Box)
        self.img_label.setObjectName("img_label")
        Camera.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Camera)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Camera.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Camera)
        self.statusbar.setObjectName("statusbar")
        Camera.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Camera)
        self.actionExit.setObjectName("actionExit")
        self.actionStartCamera = QtWidgets.QAction(Camera)
        self.actionStartCamera.setObjectName("actionStartCamera")
        self.actionStopCamera = QtWidgets.QAction(Camera)
        self.actionStopCamera.setObjectName("actionStopCamera")
        self.actionSettings = QtWidgets.QAction(Camera)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOpen_File = QtWidgets.QAction(Camera)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionAhsh = QtWidgets.QAction(Camera)
        self.actionAhsh.setObjectName("actionAhsh")
        self.menuFile.addAction(self.actionStartCamera)
        self.menuFile.addAction(self.actionStopCamera)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(Camera)
        self.captureWidget.setCurrentIndex(0)
        self.SaveButton.clicked.connect(Camera.Save_to_excel)
        self.actionExit.triggered.connect(Camera.close)
        self.Newtemplate.clicked.connect(Camera.configureSavetemplate)
        self.actionStartCamera.triggered.connect(Camera.startCamera)
        self.actionStopCamera.triggered.connect(Camera.stopCamera)
        self.actionOpen_File.triggered.connect(Camera.configureOpenExcels)
        QtCore.QMetaObject.connectSlotsByName(Camera)

    def retranslateUi(self, Camera):
        _translate = QtCore.QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Camera"))
        self.SaveButton.setText(_translate("Camera", "Save"))
        self.Newtemplate.setText(_translate("Camera","Extract Template"))
        self.captureWidget.setTabText(self.captureWidget.indexOf(self.tab_2), _translate("Camera", "Data Processing"))
        self.img_label.setText(_translate("Camera", "Please Open Excels file "))
        self.menuFile.setTitle(_translate("Camera", "File"))
        self.actionExit.setText(_translate("Camera", "Exit"))
        self.actionStartCamera.setText(_translate("Camera", "Start Camera"))
        self.actionStopCamera.setText(_translate("Camera", "Stop Camera"))
        self.actionSettings.setText(_translate("Camera", "Settings"))
        self.actionOpen_File.setText(_translate("Camera", "Open File"))
        self.actionAhsh.setText(_translate("Camera", "ahsh"))

